<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Modules\Queries\GetAllModulesWithPermissions\**" />
    <Compile Remove="Features\Modules\Queries\GetModuleWithPermissions\**" />
    <Compile Remove="Features\Roles\Commands\AssignPermissionsToRole\**" />
    <Compile Remove="Features\Roles\Queries\GetRolesByPermissionId\**" />
    <Compile Remove="Features\Roles\Queries\GetRoleWithPermissions\**" />
    <Compile Remove="Features\Role\Commands\AssignPermissionsToRole\**" />
    <Compile Remove="Features\Role\Queries\GetRolesByPermissionId\**" />
    <Compile Remove="Features\Role\Queries\GetRoleWithPermissions\**" />
    <Compile Remove="Interfaces\ICity\**" />
    <Compile Remove="Interfaces\ICountry\**" />
    <Compile Remove="Interfaces\IProduct\**" />
    <Compile Remove="Interfaces\IState\**" />
    <EmbeddedResource Remove="Features\Modules\Queries\GetAllModulesWithPermissions\**" />
    <EmbeddedResource Remove="Features\Modules\Queries\GetModuleWithPermissions\**" />
    <EmbeddedResource Remove="Features\Roles\Commands\AssignPermissionsToRole\**" />
    <EmbeddedResource Remove="Features\Roles\Queries\GetRolesByPermissionId\**" />
    <EmbeddedResource Remove="Features\Roles\Queries\GetRoleWithPermissions\**" />
    <EmbeddedResource Remove="Features\Role\Commands\AssignPermissionsToRole\**" />
    <EmbeddedResource Remove="Features\Role\Queries\GetRolesByPermissionId\**" />
    <EmbeddedResource Remove="Features\Role\Queries\GetRoleWithPermissions\**" />
    <EmbeddedResource Remove="Interfaces\ICity\**" />
    <EmbeddedResource Remove="Interfaces\ICountry\**" />
    <EmbeddedResource Remove="Interfaces\IProduct\**" />
    <EmbeddedResource Remove="Interfaces\IState\**" />
    <None Remove="Features\Modules\Queries\GetAllModulesWithPermissions\**" />
    <None Remove="Features\Modules\Queries\GetModuleWithPermissions\**" />
    <None Remove="Features\Roles\Commands\AssignPermissionsToRole\**" />
    <None Remove="Features\Roles\Queries\GetRolesByPermissionId\**" />
    <None Remove="Features\Roles\Queries\GetRoleWithPermissions\**" />
    <None Remove="Features\Role\Commands\AssignPermissionsToRole\**" />
    <None Remove="Features\Role\Queries\GetRolesByPermissionId\**" />
    <None Remove="Features\Role\Queries\GetRoleWithPermissions\**" />
    <None Remove="Interfaces\ICity\**" />
    <None Remove="Interfaces\ICountry\**" />
    <None Remove="Interfaces\IProduct\**" />
    <None Remove="Interfaces\IState\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Common\Interfaces\IAuditableCreateRequest.cs" />
    <Compile Remove="Common\Interfaces\IAuditableRequest.cs" />
    <Compile Remove="Common\Interfaces\IAuditableUpdateRequest.cs" />
    <Compile Remove="Services\AuthService.cs" />
    <Compile Remove="Services\CityService.cs" />
    <Compile Remove="Services\CountryService.cs" />
    <Compile Remove="Services\ProductService.cs" />
    <Compile Remove="Services\StateService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageReference Include="CSharpFunctionalExtensions.FluentAssertions" Version="3.0.0" />
    <PackageReference Include="FluentAssertions.CSharpFunctionalExtensions" Version="1.0.2" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
	  <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="12.3.0" />
    <PackageReference Include="MediatR.Extensions.FluentValidation.AspNetCore" Version="6.0.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommercePlatform.Domain\ECommercePlatform.Domain.csproj" />
  </ItemGroup>

</Project>
